### ISSUE TITLE
Vecka 1 - godkänd!

### ISSUE THREAD

**Issue by augber** [Havocreature/GithubCommitBot#23]
Hej,

Du är godkänd för vecka 1. Jag tycker att din projektbeskrivning är utförlig och att ditt projekt är väldigt ambitiöst för den här typen av kurs. Din projektplan är också utförlig, och delar upp projektet i logiska arbetsenheter. Blir kul att se hur sofistikerad du hinner få boten.

**Comment by Havocreature** [comment]
Hej! 

Bra :) Tyvärr har jag i senare skede kommit på att jag borde ha kollat om mina bibliotek hade ordentlig dokumentation... nltk visste jag sedan innan hade bra docs (till och med en hel bok!) men PyGithub och Github API dokumentationen har inte alls varit bra. Så jag ligger lite efter. Men borde nog kunna få ordentlig rullning på saker och ting snart :)
